// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MovieApi.Migrations
{
    [DbContext(typeof(MovieApiContext))]
    [Migration("20260624074247_changedLists")]
    partial class changedLists
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieApi.Models.Actor", b =>
                {
                    b.Property<int>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActorId"));

                    b.Property<int>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("ActorId");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            ActorId = 1,
                            BirthYear = 1965,
                            Name = "Robert Downey Jr."
                        },
                        new
                        {
                            ActorId = 2,
                            BirthYear = 1972,
                            Name = "Gwyneth Paltrow"
                        },
                        new
                        {
                            ActorId = 3,
                            BirthYear = 1969,
                            Name = "Terrence Howard"
                        },
                        new
                        {
                            ActorId = 4,
                            BirthYear = 1952,
                            Name = "Mickey Rourke"
                        },
                        new
                        {
                            ActorId = 5,
                            BirthYear = 1967,
                            Name = "Guy Pearce"
                        });
                });

            modelBuilder.Entity("MovieApi.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Duration = 126,
                            Genre = "Action",
                            Title = "Iron Man 1",
                            Year = 2008
                        },
                        new
                        {
                            MovieId = 2,
                            Duration = 124,
                            Genre = "Action",
                            Title = "Iron Man 2",
                            Year = 2010
                        },
                        new
                        {
                            MovieId = 3,
                            Duration = 130,
                            Genre = "Action",
                            Title = "Iron Man 3",
                            Year = 2013
                        });
                });

            modelBuilder.Entity("MovieApi.Models.MovieActor", b =>
                {
                    b.Property<int>("MovieActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieActorId"));

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("MovieActorId");

                    b.HasIndex("ActorId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieActors");

                    b.HasData(
                        new
                        {
                            MovieActorId = 1,
                            ActorId = 1,
                            MovieId = 1
                        },
                        new
                        {
                            MovieActorId = 2,
                            ActorId = 2,
                            MovieId = 1
                        },
                        new
                        {
                            MovieActorId = 3,
                            ActorId = 3,
                            MovieId = 1
                        },
                        new
                        {
                            MovieActorId = 4,
                            ActorId = 1,
                            MovieId = 2
                        },
                        new
                        {
                            MovieActorId = 5,
                            ActorId = 2,
                            MovieId = 2
                        },
                        new
                        {
                            MovieActorId = 6,
                            ActorId = 4,
                            MovieId = 2
                        },
                        new
                        {
                            MovieActorId = 7,
                            ActorId = 1,
                            MovieId = 3
                        },
                        new
                        {
                            MovieActorId = 8,
                            ActorId = 2,
                            MovieId = 3
                        },
                        new
                        {
                            MovieActorId = 9,
                            ActorId = 5,
                            MovieId = 3
                        });
                });

            modelBuilder.Entity("MovieApi.Models.MovieDetails", b =>
                {
                    b.Property<int>("MovieDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieDetailsId"));

                    b.Property<int>("Budget")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("MovieTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar");

                    b.HasKey("MovieDetailsId");

                    b.HasIndex("MovieId")
                        .IsUnique()
                        .HasFilter("[MovieId] IS NOT NULL");

                    b.ToTable("Details");

                    b.HasData(
                        new
                        {
                            MovieDetailsId = 1,
                            Budget = 150,
                            Language = "english",
                            MovieId = 1,
                            MovieTitle = "Iron Man 1",
                            Synopsis = "After being captured by terrorists following a missile demonstration in Afghanistan, multi-billionaire Tony Stark uses his brilliant intellect to devise a powered armor to escape. Being an irresponsible, wealthy playboy before, he (literally) has a change of heart regarding his company policies and dedicates himself to cleaning up Stark Industries' patented weapons and taking care of the terrorist group that got their hands on them. To do so, he builds an even better suit of armor. However, not everyone in his company likes the new direction he's chosen."
                        },
                        new
                        {
                            MovieDetailsId = 2,
                            Budget = 170,
                            Language = "english",
                            MovieId = 2,
                            MovieTitle = "Iron Man 2",
                            Synopsis = "Several months after the events of Iron Man, the film deals with the consequences of Tony Stark outing himself as Iron Man and becoming the world's newest defender. His first major issue is Congressional hearings about sharing his tech, with rival (and perpetually second-place to Tony) industrialist Justin Hammer (Sam Rockwell) standing the most to gain. Despite their best efforts, Tony is untouchable: unbeatable in conferences and unstoppable as Iron Man. But his invincibility is tested by Ivan Vanko/Whiplash (Mickey Rourke), a man with a grudge against the Stark empire who is more than capable of challenging Tony's genius, as Tony is also dealing with a slowly fatal medical condition resulting from his arc reactor implant."
                        },
                        new
                        {
                            MovieDetailsId = 3,
                            Budget = 200,
                            Language = "english",
                            MovieId = 3,
                            MovieTitle = "Iron Man 3",
                            Synopsis = "When an enemy from the past targets that which industrialist Tony Stark holds most dear, he must rely on his ingenuity to protect those closest to him. Still haunted by the events from the Battle of New York, he must confront challenges from not only this old adversary but from himself as well, and finally answer a question which has plagued him from the beginning: Is he the one who defines the Iron Man suit? Or is it the suit that defines him?"
                        });
                });

            modelBuilder.Entity("MovieApi.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "OMIGOD THIS IS THE BEST MOVIE EVER!",
                            MovieId = 1,
                            MovieTitle = "Aron Man 1",
                            Rating = 5,
                            ReviewerName = "Chester A. Bum"
                        },
                        new
                        {
                            Id = 2,
                            Comment = "A distasteful look into the horrifying military complex. Also, Marvel just keeps pumping these out. This is, what, the fifth one in the series?",
                            MovieId = 1,
                            MovieTitle = "Bron Man 1",
                            Rating = 1,
                            ReviewerName = "Snooty McNitpick"
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Tony looks so hot in this one. Shame about the ending. I wrote a fanfic that fixed everything, read it at http://wwwfanfic.con/340694hgio/a/",
                            MovieId = 3,
                            MovieTitle = "Cron Man 3",
                            Rating = 5,
                            ReviewerName = "StarkLovr4908"
                        },
                        new
                        {
                            Id = 4,
                            Comment = "A fascinating adaptation of long-running comics continuity adapted into film. A shame TONY DIES IN ENDGAME!",
                            MovieId = 1,
                            MovieTitle = "Dron Man 1",
                            Rating = 5,
                            ReviewerName = "Doug Spoilerton"
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Are all these reviews made up? Whatever. I liked the movie.",
                            MovieId = 2,
                            MovieTitle = "Eron Man 2",
                            Rating = 4,
                            ReviewerName = "Richard Normalman"
                        });
                });

            modelBuilder.Entity("MovieApi.Models.MovieActor", b =>
                {
                    b.HasOne("MovieApi.Models.Actor", "Actor")
                        .WithMany("MovieActor")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("MovieApi.Models.Movie", "Movie")
                        .WithMany("MovieActor")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieApi.Models.MovieDetails", b =>
                {
                    b.HasOne("MovieApi.Models.Movie", "Movie")
                        .WithOne("MovieDetails")
                        .HasForeignKey("MovieApi.Models.MovieDetails", "MovieId");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieApi.Models.Review", b =>
                {
                    b.HasOne("MovieApi.Models.Movie", null)
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieApi.Models.Actor", b =>
                {
                    b.Navigation("MovieActor");
                });

            modelBuilder.Entity("MovieApi.Models.Movie", b =>
                {
                    b.Navigation("MovieActor");

                    b.Navigation("MovieDetails");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
